from qq275860560/base

MAINTAINER jiangyuanlin@163.com

RUN curl -o /etc/rc.local https://raw.githubusercontent.com/qq275860560/ngrinder-master/master/src/main/centos/etc/rc.local && chmod +x /etc/rc.local




		